### ISSUE TITLE
No unit changing after input validation in item creation

### ISSUE THREAD

**Issue by FabianMauz** [ipb-halle/CRIMSy#184]
After entering an amount while creating an item and changing the unit, the corresponding unit of the direct container is not changed due to a input validation which fails.

![unitChangeBug](https://user-images.githubusercontent.com/23172219/166655816-3895de94-1c84-47e2-ad8f-60032e6b1474.png)

**Comment by flange-ipb** [comment]
Unsuccessful attempt:
I tried to add OmniFaces' [`<o:skipValidators>`](https://showcase.omnifaces.org/taghandlers/skipValidators) to the `<b:selectOneMenu>` component for unit selection - no changes in the described behaviour. Also using the traditional `<f:ajax>` instead of BootsFaces' AJAX attributes does not help.
