### ISSUE TITLE
Click on  BioCloud in the navigation leads to search view

### ISSUE THREAD

**Issue by FabianMauz** [ipb-halle/CRIMSy#186]
After clicking the Biocloud header in the navigation menu, the search view should be visible.

![image](https://user-images.githubusercontent.com/23172219/168251443-3e814767-1ed6-4880-a729-90e7a63702d6.png)

**Comment by flange-ipb** [comment]
fixed by 734d6a61b2e3d3d937e9c948b78d8b41558bba88

Synopsis/discussion:
- [`<b:dropMenu>`](https://showcase.bootsfaces.de/layout/navbars.jsf#attributes) does neither have active AJAX behaviour nor an onclick event.
- An onclick event can be added via a JSF passthrough attribute. The dropMenu component adds the PT attribute to all its rendered HTML elements, i.e. the event needs to be filteted for a single element (`<li>`).
- The onclick event calls a remoteCommand, which finally fires an AJAX call. This is in contrast to the navbar navigation, which does not use AJAX.
