### ISSUE TITLE
Hardcoded logfile directory

### ISSUE THREAD

**Issue by sneumann** [ipb-halle/CRIMSy#8]
Hi, 

one of the errors running `mvn package` in some/my environment is 
`Unable to create file /usr/local/tomee/logs//ui.log java.io.IOException: Could not create directory /usr/local/tomee/logs`

=> use the `$TOMCAT_HOME` variable in https://github.com/ipb-halle/CRIMSy/blob/master/ui/src/main/resources/log4j2.xml#L5

Yours, Steffen

**Comment by sneumann** [comment]
Hm, not yet sure if that commit really worked. I am getting nasty files `CRIMSy/ui/${sys:TOMCAT_HOME}/`
Search http://logging.apache.org/log4j/2.x/manual/configuration.html
for `sys:` on environment variable resolution. We are using `log4j-core-2.13.1.jar` .
Yours, Steffen

**Comment by FabianMauz** [comment]
The problem occurred when using the original logger configuration. This is now replaced by a test logging configuration adapted to the test environment. ([35f4332])

Another problem occurred due to the use of a test database sequence that had violated the timeliness of the tests.([9ac82d0])

Finally, there is still an error in the correct injection of the KeyManager in the CI environment. As a workaround I have wrapped the tests in a try-catch block until the problem is completely solved.([e7de40e]). I will open another issue for that specific problem.
